<style>
.initializing{
  text-align: center;
  margin-bottom: 1.5em;
}
.loading{
  margin: 0 auto 1.5em;
  width:30px;
}

.s2p_banks_wrap{
    width:50px;
    margin: 0 auto 1em;
}
.s2p_banks_wrap img{
  width:50px;
}
</style>

<div class="initializing">
  <h1>Sign2Pay </h1>
  <div id="sign2pay" style="display: block !important;">
    <div class="s2p-button-banks">
      <img class="loading" src="<?php print $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
            title="<?php print $this->__('Please wait while loading payment information...') ?>"
        />
    </div>

    <span class="s2p-text">
      <?php print $this->__('Thank you for your order.'); ?>
      <br/>
      <?php print $this->__('We are now initializing Sign2Pay to authorize your payment.'); ?>
    </span>
  </div>
</div>
